### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by gaurishhs** [Danktuary/react-discord-message#27]
Add support for slash commands

**Comment by Danktuary** [comment]
Hi, you can use [`@discord-message-components/react`](https://github.com/Danktuary/discord-message-components/blob/main/packages/react/README.md) which includes components for slash commands and more.

**Comment by abhigyantrips** [comment]
> Hi, you can use [`@discord-message-components/react`](https://github.com/Danktuary/discord-message-components/blob/main/packages/react/README.md?rgh-link-date=2022-01-28T15%3A19%3A22Z) which includes components for slash commands and more.

Hiya, had a few questions regarding `@discord-message-components/react` :

1. Does `@discord-message-components/react` lack any feature that `react-discord-message` has? I've been using it for a while, because of Interactions support.
2. Where can I open issues/contribute for that package?

Amazing work btw. I've been using `@discord-message-components/react` for a while, and it has been very useful.

**Comment by Danktuary** [comment]
@abhigyantrips 

1. `@discord-message-components/react` can be considered as a better version of `react-discord-message`; it was completely rewritten with many fixes and additions.
2. The repo can be found here: https://github.com/Danktuary/discord-message-components

And thanks! 😄
